pull_request_template:
  description: |
    Please include a summary of the change and which issue is fixed.
    Also include relevant motivation and context.

  fixes_issue: ""  # ex: "#123"

  type_of_change:
    bug_fix: false
    new_feature: false
    breaking_change: false
    documentation_update: false

  how_has_this_been_tested: |
    Please describe the tests that you ran to verify your changes.
    Include details of your testing environment and the test cases you used.

  tests:
    unit_tests: false
    integration_tests: false
    manual_tests: false

  checklist:
    code_style_guidelines: false
    self_review_done: false
    commented_code: false
    documentation_updated: false
    no_new_warnings: false
    tests_added: false
    unit_tests_pass: false
