name: persistent_device_id
description: A Flutter plugin that provides a persistent app-scoped device ID for Android and iOS.
version: 2.0.0
homepage: https://github.com/maeltoukap/persistent_device_id
repository: https://github.com/maeltoukap/persistent_device_id
issue_tracker: https://github.com/maeltoukap/persistent_device_id/issues
documentation: https://github.com/maeltoukap/persistent_device_id/blob/main/README.md
topics:
  - device-id
  - persistent-storage
  - android
  - ios
screenshots:
  - description: The persistent_device_id package logo.
    path: assets/persistent_device_id_logo.png

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: persistent_device_id.maeltoukap.me
        pluginClass: PersistentDeviceIdPlugin
      ios:
        pluginClass: PersistentDeviceIdPlugin
