blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/maeltoukap/persistent_device_id/blob/main/README.md
    about: Check out our documentation to learn more.
  - name: Support
    url: devmael09@gmail.com
    about: Contact us to discuss your questions and issues.